[package]
name = "api"
version = "0.1.0"
description = "An example Tauri Application showcasing the api"
edition = "2021"
rust-version = "1.77.2"
license = "Apache-2.0 OR MIT"

[lib]
name = "api_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { path = "../../../crates/tauri-build", features = [
  "codegen",
  "isolation",
] }

[dependencies]
serde_json = "1"
serde = { version = "1", features = ["derive"] }
tiny_http = "0.11"
log = "0.4.21"
tauri-plugin-sample = { path = "./tauri-plugin-sample/" }
tauri-plugin-http = { git = "https://github.com/Eulogizethesun/plugins-workspace", branch = "ohdev-git" }
tauri-plugin-os = { git = "https://github.com/Eulogizethesun/plugins-workspace", branch = "ohdev-git" }
tauri-plugin-fs = { git = "https://github.com/Eulogizethesun/plugins-workspace", branch = "ohdev-git" }
tauri-plugin-shell = { git = "https://github.com/Eulogizethesun/plugins-workspace", branch = "ohdev-git" }
tauri-plugin-clipboard-manager = { git = "https://github.com/Eulogizethesun/plugins-workspace", branch = "ohdev-git" }
tauri-plugin-process = { git = "https://github.com/Eulogizethesun/plugins-workspace", branch = "ohdev-git" }
tauri-plugin-updater = { git = "https://github.com/Eulogizethesun/plugins-workspace", branch = "ohdev-git" }
tauri-plugin-autostart = { git = "https://github.com/Eulogizethesun/plugins-workspace", branch = "ohdev-git" }
tauri-plugin-log = { git = "https://github.com/Eulogizethesun/plugins-workspace", branch = "ohdev-git" }
chrono = "0.4"
url = "2"

[target.'cfg(not(target_env = "ohos"))'.dependencies]
tauri-plugin-notification = { git = "https://github.com/Eulogizethesun/plugins-workspace", branch = "ohdev-git" }
tauri-plugin-dialog = { git = "https://github.com/Eulogizethesun/plugins-workspace", branch = "ohdev-git" }

[target.'cfg(target_env = "ohos")'.dependencies]
napi-ohos = { version = "1.1" }
napi-derive-ohos = { version = "1.1" }
hilog = "*"
tauri-plugin-dialog = { git = "https://github.com/Eulogizethesun/plugins-workspace", branch = "ohdev-git" }
tauri-plugin-single-instance = { git = "https://github.com/Eulogizethesun/plugins-workspace", branch = "ohdev-git" }

[dependencies.tauri]
path = "../../../crates/tauri"
features = [
  "protocol-asset",
  "image-ico",
  "image-png",
  "isolation",
  "macos-private-api",
  "tray-icon",
]

[dev-dependencies.tauri]
path = "../../../crates/tauri"
features = ["test"]

[features]
prod = ["tauri/custom-protocol"]

[profile.release]
# 开启调试信息（最重要）
debug = true

# 可选：保留行号、变量名等更完整的调试信息（gdb、lldb、日志回溯都能用）
strip = false
opt-level = 0  # 关闭优化，调试最清晰
