#!/bin/bash
# Clean stale autogenerated ACL permission files that no longer match build.rs commands.
#
# Problem: tauri-build's autogenerate_command_permissions() only writes .toml files,
# never deletes them. When commands are removed from build.rs, residual files in the
# gitignored permissions/autogenerated/ directory silently grant ACL permissions,
# causing inconsistent behavior between clean and incremental builds.
#
# This script handles both app-level and plugin-level autogenerated permissions:
#   - App:    {root}/build.rs → {root}/permissions/autogenerated/*.toml
#   - Plugin: {root}/*/build.rs → {root}/*/permissions/autogenerated/commands/*.toml
#
# Usage:
#   bash clean-stale-acl.sh <src-tauri-dir>
#
# Example:
#   bash clean-stale-acl.sh examples/api/src-tauri

set -e

ROOT="${1:-.}"

TOTAL_REMOVED=0

# Extract expected command names from a build.rs file.
# Supports two patterns:
#   1. .commands(&["cmd1", "cmd2", ...])  — tauri_build AppManifest / InlinedPlugin
#   2. const COMMANDS: &[&str] = &["cmd1", ...]  — tauri_plugin::Builder
extract_commands() {
    local build_rs="$1"

    # Pattern 1: .commands(&[...]) blocks (may span multiple lines)
    sed -n '/\.commands(&\[/,/])/p' "$build_rs" 2>/dev/null \
        | grep -oP '"\K[a-zA-Z0-9_]+(?=")' 2>/dev/null || true

    # Pattern 2: const COMMANDS: &[&str] = &[...] (may span multiple lines)
    # Use awk: sed range fails when ] is on the same line as the start pattern.
    # End on ]; at end-of-line (avoids false match on ] inside &[&str] type).
    awk '/const COMMANDS/{p=1} p{print} p && /\][[:space:]]*;[[:space:]]*$/{p=0}' "$build_rs" 2>/dev/null \
        | grep -oP '"\K[a-zA-Z0-9_]+(?=")' 2>/dev/null || true
}

# Clean stale .toml files from an autogenerated directory.
# Args: build_rs_path autogen_dir [subdir]
#   subdir: optional subdirectory within autogen_dir (e.g. "commands" for plugins)
process_target() {
    local build_rs="$1"
    local autogen_dir="$2"
    local subdir="${3:-}"

    local scan_dir="$autogen_dir"
    if [ -n "$subdir" ]; then
        scan_dir="$autogen_dir/$subdir"
    fi

    # Skip if either the build.rs or the autogenerated directory doesn't exist
    if [ ! -f "$build_rs" ] || [ ! -d "$scan_dir" ]; then
        return
    fi

    # Build list of expected .toml filenames from build.rs commands
    local expected_files
    expected_files=$(extract_commands "$build_rs" | while read -r cmd; do
        [ -n "$cmd" ] && echo "${cmd}.toml"
    done)

    # If no commands found in build.rs, skip (nothing to compare against)
    if [ -z "$expected_files" ]; then
        return
    fi

    # Scan .toml files and remove any not in the expected list
    local removed=0
    for toml_file in "$scan_dir"/*.toml; do
        [ -f "$toml_file" ] || continue
        local filename
        filename=$(basename "$toml_file")
        if ! echo "$expected_files" | grep -qxF "$filename"; then
            echo "  Removing stale permission: $filename (from $scan_dir)"
            rm -f "$toml_file"
            removed=$((removed + 1))
        fi
    done

    TOTAL_REMOVED=$((TOTAL_REMOVED + removed))
}

# ─── App-level: {root}/build.rs → {root}/permissions/autogenerated/ ───
process_target "$ROOT/build.rs" "$ROOT/permissions/autogenerated"

# ─── Plugin-level: {root}/*/build.rs → {root}/*/permissions/autogenerated/commands/ ───
for plugin_dir in "$ROOT"/*/; do
    [ -d "$plugin_dir" ] || continue
    # Strip trailing slash for consistent path construction
    plugin_dir="${plugin_dir%/}"
    process_target "$plugin_dir/build.rs" "$plugin_dir/permissions/autogenerated" "commands"
done

# ─── Summary ───
if [ "$TOTAL_REMOVED" -gt 0 ]; then
    echo "  Cleaned $TOTAL_REMOVED stale permission file(s)."
else
    echo "  All permission files are consistent."
fi
